export const USERLOADING="USERLOADING",
export const USERLOADED="USERLOADED",
export const AUTH_ERROR="AUTH_ERROR",
export const LOGIN_SUCCESS="LOGIN_SUCCESS",
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS",
export const REGISTER_SUCCESS="REGISTER_SUCCESS",
export const GET_ERRORS='GET_ERRORS',
export const CLEAR_ERRORS='LEAR_ERROR';
